"""Notifier module: Send change notifications to an SNS topic."""

import logging
import os

import boto3

logger = logging.getLogger(__name__)


def get_sns_client():
    """Get the SNS client."""
    region = os.environ.get("AWS_REGION_NAME", "us-east-1")
    return boto3.client("sns", region_name=region)


def send_notification(summary: str, changed_pages: list[dict]):
    """Send the change summary to the SNS topic.

    Args:
        summary: Summary text generated by Bedrock.
        changed_pages: List of pages that have changed.
    """
    topic_arn = os.environ.get("SNS_TOPIC_ARN")
    if not topic_arn:
        logger.warning("SNS_TOPIC_ARN not set. Skipping notification.")
        return

    client = get_sns_client()

    subject = f"AWS Doc Update: {len(changed_pages)} page(s) changed"
    # SNS subject has a 100-character limit
    if len(subject) > 100:
        subject = subject[:97] + "..."

    message = _format_message(summary, changed_pages)

    try:
        client.publish(
            TopicArn=topic_arn,
            Subject=subject,
            Message=message,
        )
        logger.info(f"Notification sent to {topic_arn}")
    except Exception as e:
        logger.error(f"Failed to send notification: {e}")
        raise


def _format_message(summary: str, changed_pages: list[dict]) -> str:
    """Format the SNS notification message."""
    lines = [
        "=" * 60,
        "AWS Documentation Change Notification",
        "=" * 60,
        "",
        f"Pages changed: {len(changed_pages)}",
        "",
        "Changed pages:",
    ]

    for page in changed_pages:
        status = "NEW" if page.get("is_new") else "UPDATED"
        lines.append(f"  [{status}] {page['title']}")
        lines.append(f"           {page['url']}")

    lines.extend(
        [
            "",
            "-" * 60,
            "AI Summary:",
            "-" * 60,
            "",
            summary,
            "",
            "=" * 60,
        ]
    )

    return "\n".join(lines)
